x = int(input("enter your first number: "))
y = int(input("enter you second number: "))
print("sum of both numbers: " , x+y)
print("Difference of both numbers: " , x-y)
print("Product of both numbers: " , x*y)
print("Quotant of both numbers: " , x/y)